fint:
  application-id: fint-kontroll-assignment-catalog
  cache:
    defaultCacheEntryTimeToLiveMillis: 518400000
    defaultCacheHeapSize: 1000000
  integration:
    service:
      authorized-role: https://role-catalog.vigoiks.no/vigo/samtykke/user
  kontroll:
    assignment-catalog:
      pagesize: 50
      publishing:
          initial-delay: 1
          fixed-delay: 15

    opa:
      url: http://fint-kontroll-opa:8181/v1/data/accessmanagement
    authorization:
      authorized-role: 'https://role-catalog.vigoiks.no/vigo/kontroll/user'
      authorized-admin-role: 'https://role-catalog.vigoiks.no/vigo/kontroll/admin'
      authorized-org-id: 'vigo.no'

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.felleskomponent.no/nidp/oauth/nam
  profiles:
    include:
      - db
      - kafka
logging:
  level:
    root: INFO
    org.apache.kafka: INFO
server:
  error:
    include-message: always
