create table assignmentemberships (
    id int8 generated by default as identity,
    user_id int8,
    primary key (id));

create table assignment_resources (
    id int8 generated by default as identity,
    group_object_id varchar(255),
    primary key (id));

create table assignment_roles (
    id int8 generated by default as identity,
    primary key (id));

create table assignments (
    id int8 generated by default as identity,
    assigner_role_ref int8,
    assigner_ref int8,
    assignment_date timestamp,
    assignment_id varchar(255),
    organization_unit_id varchar(255),
    resource_ref int8,
    role_ref int8,
    user_ref int8,
    valid_from timestamp,
    valid_to timestamp,
    primary key (id));

create table flattened_assignments (
    id int8 generated by default as identity,
    assignment_id int8,
    group_object_id varchar(255),
    user_object_id varchar(255),
    primary key (id));

create table users (
    id int8 generated by default as identity,
    user_object_id varchar(255),
    primary key (id));
